### ISSUE TITLE
 "OSError: file notebooks/openasl-v1.0/openasl-bpe25000-tokenizer-uncased/config.json not found", I check the file,it is actually don't exit,,why?

### ISSUE THREAD

**Issue by 1578661255** [HenryLittle/GloFE#6]
tokenizer      notebooks/openasl-v1.0/openasl-bpe25000-tokenizer-uncased
         eos_token      </s>
       max_gen_tks      35
         num_beams      5
        vocab_size      25000
     dim_embedding      768
        activation      gelu
        norm_first      False
       mask_future      True
          froze_vb      False
           num_enc      4
   dim_forward_enc      1024
         nhead_enc      8
       dropout_enc      0.1
            pe_enc      True
          mask_enc      True
           num_dec      4
   dim_forward_dec      1024
         nhead_dec      8
       dropout_dec      0.1
                ls      0.2
          inter_cl      True
   inter_cl_margin      0.4
    inter_cl_alpha      1.0
    inter_cl_vocab      5523
   inter_cl_we_dim      300
  inter_cl_we_path      notebooks/openasl-v1.0/uncased_filtred_glove_VN_embed.pkl
     pose_backbone      PartedPoseBackbone
Traceback (most recent call last):
  File "/home/ma-user/anaconda3/envs/glofe/lib/python3.8/site-packages/transformers/configuration_utils.py", line 363, in get_config_dict
    resolved_config_file = cached_path(
  File "/home/ma-user/anaconda3/envs/glofe/lib/python3.8/site-packages/transformers/file_utils.py", line 957, in cached_path
    raise EnvironmentError("file {} not found".format(url_or_filename))
OSError: file notebooks/openasl-v1.0/openasl-bpe25000-tokenizer-uncased/config.json not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_openasl_pose_DDP_inter_VN.py", line 649, in <module>
    main()
  File "train_openasl_pose_DDP_inter_VN.py", line 584, in main
    tokenizer = AutoTokenizer.from_pretrained(
  File "/home/ma-user/anaconda3/envs/glofe/lib/python3.8/site-packages/transformers/tokenization_auto.py", line 298, in from_pretrained
    config = AutoConfig.from_pretrained(pretrained_model_name_or_path, **kwargs)
  File "/home/ma-user/anaconda3/envs/glofe/lib/python3.8/site-packages/transformers/configuration_auto.py", line 330, in from_pretrained
    config_dict, _ = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/ma-user/anaconda3/envs/glofe/lib/python3.8/site-packages/transformers/configuration_utils.py", line 382, in get_config_dict
    raise EnvironmentError(msg)
OSError: Can't load config for 'notebooks/openasl-v1.0/openasl-bpe25000-tokenizer-uncased'. Make sure that:

- 'notebooks/openasl-v1.0/openasl-bpe25000-tokenizer-uncased' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'notebooks/openasl-v1.0/openasl-bpe25000-tokenizer-uncased' is the correct path to a directory containing a config.json file

**Comment by 1578661255** [comment]
--tokenizer (Optional): path to tokenizer folder, don't need to modify unless you want to use another one


so i don't modify this
